version: '3'

services:
  graphql:
    build: ./server
    ports:
      - 4000:4000
    links:
    - neo4j
    depends_on:
    - neo4j
    environment:
      - NEO4J_URI= bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=graphrm

  neo4j:
    build: ./db
    ports:
      # Bolt port
      - 7474:7474
      - 7687:7687
    environment:
      # Enable APOC
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_AUTH=neo4j/graphrm
    volumes:
    - ./data:/data